version: '3'

services:
  mysql-db:
    image: mysql
    container_name: mysql-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
#      - .sql:/docker-entrypoint-initdb.d/
      - .sql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: learning_center
      MYSQL_ROOT_PASSWORD: sprincourse

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db

  payment-service:
    build: payment-service/
    container_name: payment-service
    ports:
      - "8081:8081"
    depends_on:
      - mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: springcourse
    restart: always

  study-center:
    build: study-center/
    container_name: study-center
#    ports:
#      - "8080:8080"
    depends_on:
      - mysql-db
      - payment-service
    environment:
      MYSQL_ROOT_PASSWORD: springcourse
      SOAP_URL: http://localhost:8081/api/soap
    restart: on-failure