version: '3'

services:
  cloud-config:
    build: spring-cloud-config-server/
    container_name: cloud-config
    ports:
      - "8888:8888"
    restart: always

  mysql-db:
    image: mysql
    container_name: mysql-db
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    ports:
      - "3306:3306"
    volumes:
      - .sql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: learning_center
      MYSQL_ROOT_PASSWORD: sprincourse

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db

  payment-service:
    build: payment-service/
    container_name: payment-service
    ports:
      - "8081:8081"
    depends_on:
      - mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: springcourse
      DB: mysql-db
    restart: on-failure

  study-center:
    build: study-center/
    container_name: study-center
    ports:
      - "8082:8080"
    depends_on:
      - mysql-db
      - payment-service
      - cloud-config
    volumes:
      - ./log:/logs
    environment:
      MYSQL_ROOT_PASSWORD: springcourse
      SOAP_URL: http://payment-service:8081/api/soap
      DB: mysql-db
      CONFIG_URL: http://cloud-config:8888
    restart: always
