logging:
  enable: true
  loggable:
    packages:
      - com.ilzirabalobanova.epam.learning_center.service.impl
    methods:
      - deleteStudent
      - addStudent
      - sortAndShowStudents
      - updateStudent
      - updateStudent


spring:
  datasource:
#    db-1:
#      username: bestuser
#      password: bestuser
#      url: jdbc:mysql://localhost:3306/learning_center?serverTimezone=UTC
#      driver-class-name: com.mysql.cj.jdbc.Driver
#    db-2:
      url: jdbc:h2:mem:mydb
      username: sa
      password: password
      driverClassName: org.h2.Driver
      jpa:
        spring.jpa.database-platform: org.hibernate.dialect.H2Dialect


resources:
    student-repository: JpaStudentRepository
#    student-repository: JDBCStudentRepository
#    module-repository: JpaModuleRepository
    module-repository: JDBCModuleRepository
#    mark-repository: JpaMarkRepository
    mark-repository: JDBCMarkRepository
