logging:
  enable: true
  loggable:
    packages:
      - com.ilzirabalobanova.epam.learning_center.service.impl
    methods:
      - deleteStudent
      - addStudent
      - sortAndShowStudents
      - updateStudent
      - updateStudent


spring:
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp