logging:
  enable: true
  loggable:
    packages:
      - com.ilzirabalobanova.epam.learning_center.service.impl
    methods:
      - deleteStudent
      - addStudent
      - sortAndShowStudents
      - updateStudent
      - updateStudent


spring:
  datasource:
      username: bestuser
      password: bestuser
      url: jdbc:mysql://localhost:3306/learning_center?serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver

resources:
    repository: JPA
#    repository: JDBC
