FROM openjdk:11.0.6-jre-buster
COPY build/libs/spring-cloud-config-server-1.0-SNAPSHOT.jar spring-cloud-config-server-1.0-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","spring-cloud-config-server-1.0-SNAPSHOT.jar"]