//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.14 at 12:23:33 PM SAMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.ilzirabalobanova.com/spring/ws/payments", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.ilzirabalobanova.epam.entity.payments;
