spring:
  application:
    name: study-center
  config:
    import: optional:configserver:http://${CONFIG_URL:localhost}:8888
  profiles:
    active: prod
    #    active: dev

resources:
  repository: JPA
  #    repository: JDBC